name: check
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v17
        with:
          name: aostanin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.ref != 'refs/heads/main' }}
      - run: nix flake check --print-build-logs
      - run:
          nix build --print-build-logs .#kvmd .#kvmd-fan .#pikvm-packages
          .#janus-assets
      - name: build systems (patched kernel)
        if: github.ref == 'refs/heads/main'
        run:
          nix build --print-build-logs
          .#nixosConfigurations.v2-hdmi-rpi4.config.system.build.toplevel
          .#nixosConfigurations.v2-hdmiusb-rpi4.config.system.build.toplevel
          .#nixosConfigurations.v3-hdmi-rpi4.config.system.build.toplevel
